export const ERROR_CODES = {
  // Generic
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Auth
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NEW_PASSWORD_REQUIRED: 'NEW_PASSWORD_REQUIRED',

  // Employee
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_DUPLICATE: 'EMPLOYEE_DUPLICATE',

  // Payroll
  PAYROLL_NOT_FOUND: 'PAYROLL_NOT_FOUND',
  PAYROLL_CALC_ERROR: 'PAYROLL_CALC_ERROR',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
};

export const SUCCESS_CODES = {
  // Generic
  SUCCESS: 'SUCCESS',

  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  PASSWORD_RESET_TOKEN_CREATED: 'PASSWORD_RESET_TOKEN_CREATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  // Employee
  EMPLOYEE_FETCHED: 'EMPLOYEE_FETCHED',
  EMPLOYEE_LIST_FETCHED: 'EMPLOYEE_LIST_FETCHED',
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_DELETED: 'EMPLOYEE_DELETED',

  // Payroll
  PAYROLL_FETCHED: 'PAYROLL_FETCHED',
  PAYROLL_LIST_FETCHED: 'PAYROLL_LIST_FETCHED',
  PAYROLL_CREATED: 'PAYROLL_CREATED',
  PAYROLL_UPDATED: 'PAYROLL_UPDATED',

  // Roles
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
};
